name: Test External

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # This CI step was originally designed to ensure that we don't break the build because there are optional packages 'mixed in'.
  # IMO, we can probably do this or a better way...
  install-and-test:
    runs-on: ubuntu-20.04

    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0 # nx recipe

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - uses: nrwl/nx-set-shas@v3 # nx recipe

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-optional
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build (Affected)
        run: NODE_ENV=production yarn nx affected -t build --parallel=3 # nx recipe
