# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Packages

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-publish:
    env:
      HUSKY: 0

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - name: Use Github Personal Access Token
        run: git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf ssh://git@github.com/

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: NODE_ENV=production yarn build

      - name: Fetch Latest Tags
        run: |
          git fetch --tags

      - name: Set NPM Token
        run: |
          npm set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_PUBLISH_TOKEN }}
          npm whoami

      - name: Publish
        run: |
          yarn lerna publish from-git --yes --allowBranch=main

      # Aqui viene el OB
      # Clone monoservice
      # NPM Upgrade
      # Git add -A
      # GH PR

      - name: Clone Monoservice
        uses: actions/checkout@v3
        with:
          path: monoservice
          repository: 'git@github.com:segmentio/integrations.git'
          token: ${{ secrets.GH_PAT }}

      - name: Upgrade
        run: |
          yarn upgrade --latest @segment/actions-core @segment/action-destinations

      - name: Commit
        run: |
          git add -A && git commit -m "Upgrade Actions (Test)"
        
      - name: Pull Request
        run: |
          gh pr create -d -t "Upgrade Actions" --body "Test" 
